### ISSUE TITLE
Seems to be totally buggy in French

### ISSUE THREAD

**Issue by gaetan80** [vanderlee/phpSyllable#4]
Totally buggy in French 

$syllable = new Syllable('fr');

//etc...
$syllable->splitWord('constitution');  returns Array ( [0] => constitution ) 
$syllable->splitWord('alphabet');  returns Array ( [0] => alphabet ) instead of al-pha-bet
$syllable->splitWord('formation'); Array ( [0] => for [1] => mation ) instead of for-ma-tion

Now, what I get when I set to Finnish.  new Syllable('fi');
Array ( [0] => cons [1] => ti [2] => tu [3] => tion )
Array ( [0] => alp [1] => ha [2] => bet )
Array ( [0] => for [1] => ma [2] => tion )

How can I fix that ?

**Comment by vanderlee** [comment]
French does indeed seem to have a shortage of hyphens compared to the other languages (although norwegian seems to have a similar issue).

My guess is that the .tex files aren't very good. .tex files are the hyphenation files used by TeX (and it's ilk). I don't generate these myself. You could try to install TeX and see how it handles the Frentch hyphenation.

There may also be an issue with the accents in the .tex files (even though your examples do not use them). I'll have to check on that.

**Comment by vanderlee** [comment]
It seems to be the apostrophe (') in the /patterns in the .tex files.
Syllable was ignoring the apostrophe, which caused to many negatives for hyphenation.
I've got part of the problem fixed, but suspect there are a few related issues elsewhere and my current solution may not be optimal or complete. I'll keep you posted.

FWIW, my current fix hyphenates your words as: consti-tu-tion al-pha-bet for-ma-tion

**Comment by vanderlee** [comment]
Do you have any multi-syllable French word with an apostrophe, like "jusqu'au", but longer, including how they should be hyphenated? It's kinda hard debugging without knowing the language :)

**Comment by vanderlee** [comment]
I've just pushed a new version (1.4) into the repository, which should fix this issue.

It also includes a lot of updated and a few new .tex files.

Please test if it works for you and let me know.

**Comment by gaetan80** [comment]
Thank you. 

Sorry, correct hyphenation for "constitution" is cons-ti-tu-tion.

"apostrophe" returns apos-trophe instead of a-pos-tro-phe. 

Note : There are four syllables, but in French it's not allowed to leave only one letter when you truncate a word at a line break. So If i want to split only the word to count the syllables, the correct answser will be this one : a-pos-tro-phe. If I want to split the text to evaluate where I can break the line, the correct answer is apos-tro-phe.

"l'apostrophe" should return l'a-pos-tro-phe. Now it's ok, because there are two letters.

I tried "aujourd'hui"  (today). It works fine :  [0] => au [1] => jour [2] => d'hui.

If you want to try by yourself : http://www.plumefrancaise.fr/fr/c%C3%A9sure/apostrophe

**Comment by gaetan80** [comment]
plumefrancaise.fr is a tool I found. Don't know how it works...

**Comment by vanderlee** [comment]
I think this might be as good as it gets right now. "apostrophe" seems to be according to the .tex rules for French. The only way to fix that is to try and get the French .tex files changed.

Note that no hyphenation algorithm is going to be perfect. The .tex files, and hence phpSyllable err on the side of safety rather than completeness; when in doubt, no hyphen. Therefore you may occasionally have missing hyphens. French in particular seems to be very much hand-tuned, which means it's going to have some gaps.

**Comment by gaetan80** [comment]
I think you cannot rely only on the .tex files. I think phpSyllable is enough to make a line break at a right place. But actually in French, you can't count syllables with. In French, a syllable is made of only one vowel (a,e,i, etc..) or one node (ae, au, ou, etc..). So "consti" for example is not a syllable but 2 syllables : cons - ti. But you work is good enough - French is a weird language... Thank you.

**Comment by vanderlee** [comment]
Not just French. For example, in English, the word "record" is hyphenated as either "re-cord" or "rec-ord" depending on the intended meaning of the word. French .tex files contain quite long words which are explicitly only one syllable. In my native Dutch, hyphenation is dependent on the language from which a word derives, even if it no longer resembles the borrowed word. As I said; no algorithm is going to be perfect :)

I'm closing this issue, as the issue seems resolved.
