### ISSUE TITLE
Problems with hiatuses, words beginning with a vowel and more in Spanish

### ISSUE THREAD

**Issue by TeLiXj** [vanderlee/phpSyllable#6]
I know that Tex files have the information to split the words, but I don't know how fix it and maybe you can do something with them

- The first problem is with hiatuses, acording to [this article of Wikipedia](https://es.wikipedia.org/wiki/Hiato_%28fonolog%C3%ADa%29) fails in all cases

**Simple Hiatus**
> caoba -> cao-ba instead of ca-o-ba
> saeta -> sae-ta instead of sa-e-ta
> chiita -> chií-ta instead of chi-i-ta

**Acentual hiatus**
> saúco -> saú-co instead of sa-ú-co.
> sabía -> sa-bía instead of sa-bí-a.

**Sporadic hiatus**
> píe -> píe instead of pí-e
> río -> río instead of rí-o

- The other problem is with words beginning with a vowel, don't split it from the other part

> azul -> azul instead of a-zul
> etéreo -> eté-reo instead of e-té-re-o
> iluminado -> ilu-mi-na-do instead of i-lu-mi-na-do
> otero -> ote-ro instead of o-te-ro
> uniforme -> uni-for-me instead of u-ni-for-me

- And fínally more rare examples (I have many more)

> ábaco -> áb-a-co instead of á-ba-co
> emanciparse -> em-an-ci-par-se instead of e-man-ci-par-se
> separar -> se-p-a-rar instead of se-pa-rar

**Comment by vanderlee** [comment]
Hi. Thanks for reporting these.

From what I can see and test using other hyphenation implementations, the problem with these words seem to mostly stem with the Text files themselves; I can't find any other hyphenator (excluding dictionary lookups) that handle these cases any better.

As for the words ending with a syllable of only a single letter, these are expressly forbidden by the min.json file (which is itself compiled from lots of "official" Tex files). The second `2` in `"es": [2, 2],` explicitely states that the last syllable must be atleast two characters long. Similar for words starting with a single-letter syllable.

Possibly this is due to ambiguous hyphenation rules in the language itself; most language have some ambiguities, I'm assuming Spanish is no exception. The goal of the Tex files is to err on the safe side; preferably too few hyphens, but atleast at correct places, than too many as possibly incorrect places. Perhaps it's simply a matter of the Spanish Tex files being incomplete or outdated.

Since both issues seem to originate from the Tex files, your best bet is to contact either the authors of the Tex files (contact information in the file `languages/hyph-ex.tex`) or the Tex-hyphen mailing list (http://tug.org/mailman/listinfo/tex-hyphen). I could do this myself, but since I have no clue about the Spanish language, I'm in no position to argue any issues that might arise.

**Comment by TeLiXj** [comment]
In Spanish only can be a different syllable in the end of word if is a vowel and the previous letter too (sabía -> sa-bí-a) and in beginning of word, only vowels followed by a consonant and vowel (erizo -> e-ri-zo). With [1, 1] in min.js works fine for most of initial syllables, but final vowels aren't separated. 
I was tried to fix it updating Spanish Tex file from here https://www.ctan.org/tex-archive/language/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/, but the 4.7 version only fix all my rare examples.
If you want I could update these changes in a new commit. 
And I will send my doubts to this mailing list, thanks :)
