### ISSUE TITLE
Brazilian Portuguese updates

### ISSUE THREAD

**Issue by saymoncoppi** [vanderlee/phpSyllable#7]
Hello Vanderlee! 
First of all.. Congrats for your project, they save alot of time!
Im including phpSyllable into my personal project to count poetic sylables and check certain types of poems. 

I identified the same throubles that the another guy found with Spanish language, I already update tex file on the folder from http://tug.org/tex-hyphen/#languages. 

But the situation is the same... any ideas to solve this?

Best regards and congrats again.

**Comment by saymoncoppi** [comment]
Hello , i made some tests with ES pack and works to me

**Comment by vanderlee** [comment]
I think the issue is the same; the TeX hyphentation algorithm (what phpSyllable is based on) intends split syllables only when it is certain, so it's good for hyphenation, but not so good for exact counts. You can change the `min.json` file to get recognize more syllables, but that will likely produce less correct positions for hyphenation.
Your best bet would be to try and get the maintainers of the original `.tex` file and see if you can help them improve their hyphentation file.
